apiVersion: v1
data:
  mariadb-password: V2d3NUtDbHFoNQ==
  mariadb-root-password: WnF6M0Y1SUhhMA==
kind: Secret
metadata:
  creationTimestamp: "2020-04-28T00:34:38Z"
  labels:
    app: mariadb
    chart: mariadb-7.3.21
    heritage: Helm
    release: autospot-wordpress-dev
  name: autospot-wordpress-dev-mariadb
  namespace: dev
  resourceVersion: "13029873"
  selfLink: /api/v1/namespaces/dev/secrets/autospot-wordpress-dev-mariadb
  uid: 0e0038a6-c504-4333-a810-9d0f92f8f5ef
type: Opaque
