apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
    volume.kubernetes.io/selected-node: ip-10-0-137-65.ec2.internal
  creationTimestamp: "2020-04-28T00:34:39Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: mariadb
    component: master
    heritage: Helm
    release: autospot-wordpress-dev
  name: data-autospot-wordpress-dev-mariadb-0
  namespace: dev
  resourceVersion: "13029934"
  selfLink: /api/v1/namespaces/dev/persistentvolumeclaims/data-autospot-wordpress-dev-mariadb-0
  uid: e6d48cb7-15c2-4644-8dad-37b81eeb8df9
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp2
  volumeMode: Filesystem
  volumeName: pvc-e6d48cb7-15c2-4644-8dad-37b81eeb8df9
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
